### ISSUE TITLE
razer-service: No module named 'notify2'

### ISSUE THREAD

**Issue by kusayuzayushko** [pez2001/razer_chroma_drivers#158]
Can't run the daemon on Archlinux.

```
$ razer-service                                                                                    
Traceback (most recent call last):
  File "/usr/bin/razer-service", line 6, in <module>
    from razer_daemon.daemon import daemonize
  File "/usr/lib/python3.5/site-packages/razer_daemon/daemon.py", line 23, in <module>
    import razer_daemon.hardware
  File "/usr/lib/python3.5/site-packages/razer_daemon/hardware/__init__.py", line 7, in <module>
    from razer_daemon.hardware.mouse import RazerMambaChromaWireless
  File "/usr/lib/python3.5/site-packages/razer_daemon/hardware/mouse.py", line 5, in <module>
    from razer_daemon.misc.battery_notifier import BatteryManager
  File "/usr/lib/python3.5/site-packages/razer_daemon/misc/battery_notifier.py", line 8, in <module>
    import notify2
ImportError: No module named 'notify2'
```

**Comment by terrycain** [comment]
Should of raised the issue [here](https://github.com/terrycain/razer-drivers) :wink:. Install (asuming your on Ubuntu) `apt-get install -y python3-notify2`.

Has been fixed ready for the next release.

**Comment by kusayuzayushko** [comment]
Yep, installing `python-notify2` from AUR solved this.

**Comment by ghost** [comment]
Installed, it declines to work on debian stretch 9.
![screenshot from 2019-01-04 16-42-10](https://user-images.githubusercontent.com/39874132/50690905-2ec31900-1040-11e9-864b-d3c6b35e7223.png)
